version: "3"
services:
  internship:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: internship
      POSTGRES_PASSWORD: <%= ENV["INTERNSHIP_DATABASE_PASSWORD"] %>
      POSTGRES_DB: internship_production
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  db-data: {}

#Данный код представляет собой файл конфигурации Docker Compose, который определяет сервисы, 
#сети и тома, необходимые для развертывания многоконтейнерного приложения. 
#version: "3"
#Эта строка указывает версию синтаксиса Compose, используемую в данном файле. 
#В данном случае используется версия 3.
#Этот блок определяет сервисы internship и db.
#- Сервис internship собирается посредством файла Dockerfile из текущего контекста сборки и 
#проксирует порт 3000 из контейнера в хостовую систему. Также данный сервис примонтирует текущий
# каталог в /rails внутри контейнера.

#- Сервис db использует образ postgres:latest, проксирует порт 5432 из контейнера в хостовую
# систему, устанавливает переменные среды для пользователя, пароля и базы данных postgres. 
#Также сервис создает том из переменной db-data для сохранения данных postgres.

#networks:
#  backend:

#Этот блок определяет пользовательскую сеть с названием backend. Сети могут быть использованы
# для связи между контейнерами.

#volumes:
#  db-data: {}

#Этот блок определяет том с именем db-data, который будет использоваться для постоянного 
#хранения данных postgres.

#В целом, данный файл определяет контейнеры, сети и тома, необходимые для развертывания
# многоконтейнерного приложения, используя Docker Compose, и описывает связи между сервисами 
#и внешние зависимости.
